### ISSUE TITLE
Pipe a list of stables to the st2... functions 

### ISSUE THREAD

**Issue by KatherineKayMRG** [metrumresearchgroup/pmtables#168]
# Summary

As a user, I would like to pipe a list of stables to the st2article and st2report functions. 

In the previous version of pmtables we could pipe a list of stables to whichever function we wanted to use. This works

```
data_pk <- pmtables::pmt_pk
test = pt_data_inventory(data_pk,
                         by = c(Study = "STUDYf"),
                         panel = "ASIANf") %>% 
  stable(r_file = "test.R", 
         output_file = "test.tex")

st2report(.list=list(test, test))
```
and does what I need but we also used to be able to use 
```
list(test, test) %>%  st2report()
 Error: Elements 1 of tables_are_stable are not true 
```
I found this error message confusing initially because it implied my `test` was not an stable but 
eventually realised this `test %>%  st2report()` and `st2report(.list=list(test, test))` still worked.  

It would be nice to get this functionality back. If it was intentionally removed, is it possible to get a more informative error message returned?

**Comment by kylebaron** [comment]
See #194 #195
