### ISSUE TITLE
Typos in pmtables document

### ISSUE THREAD

**Issue by KatherineKayMRG** [metrumresearchgroup/pmtables#210]
<img width="616" alt="Screen Shot 2021-03-08 at 6 46 18 PM" src="https://user-images.githubusercontent.com/42553148/110480645-b7bcbb80-80b4-11eb-8853-7d2b34b02ec2.png">

<img width="554" alt="Screen Shot 2021-03-08 at 6 46 30 PM" src="https://user-images.githubusercontent.com/42553148/110480649-b8555200-80b4-11eb-8e76-736b80db5468.png">

**Comment by kylebaron** [comment]
Thank you @KatherineKayMRG ; these have been fixed.

KTB
