### ISSUE TITLE
label option for st_asis

### ISSUE THREAD

**Issue by curtisKJ** [metrumresearchgroup/pmtables#218]
# Summary

It'd be handy to be able to pass a label to `st_asis` for easy referencing in rendered documents.

**Comment by curtisKJ** [comment]
FWIW, you can make it work by doing ...

```
caption = 'Subject and Observation Summary by Study \\label{my label}'
```

**Comment by kylebaron** [comment]
Closing this; lets continue including the label like this rather than adding another argument.  You can also do this for longtable (and I might refactor that to just let the label come from the caption).
