### ISSUE TITLE
Multiple st_asis() calls w/i a code chunk prints 

### ISSUE THREAD

**Issue by curtisKJ** [metrumresearchgroup/pmtables#219]
# Summary

When using st_asis to render a table that's been written out to disk in a knitted Rmd, I'm noticing that if I have more than one call to st_asis in a chunk, it'll render the tables, but there'll be a """=latex in between successive tables. With just one call per chunk, it's OK, no message.

Per @kylebaron 

> It seems like this only happens when echo is false; probably need to put a newline after each table when printing them out.
> you can throw writeLines("") in between then tables for now
> Or in a new block

```
library(pmtables)
library(dplyr)
data <- slice(stdata(), 1:3)
data %>% stable() %>% st_asis()
writeLines("")
data %>% stable() %>% st_asis()
```

**Comment by kylebaron** [comment]
Closed for #224
