### ISSUE TITLE
pt_data_inventory to update colname/footer when I use BLQ

### ISSUE THREAD

**Issue by KatherineKayMRG** [metrumresearchgroup/pmtables#254]
# Summary

As a user, I want pt_data_inventory to change my colname/footer description for BLQ if I use `bq_col = "BLQ"`

# Tests
- tests/testthat/test-inventory-table.R
  - handle BQL and BLQ inventory table

**Comment by kylebaron** [comment]
How about this?

``` r
library(pmtables)


bq_col <- "BQL"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                      
#> [2] "BQL: below quantitation limit"       
#> [3] "MISS: missing observations (not BQL)"
#> [4] "OBS: observations"
bq_col <- "BLQ"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                      
#> [2] "BLQ: below limit of quantitation"    
#> [3] "MISS: missing observations (not BQL)"
#> [4] "OBS: observations"
```

<sup>Created on 2022-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kylebaron** [comment]
Hang on; need to fix `MISS` then.

**Comment by kylebaron** [comment]
``` r
library(pmtables)


bq_col <- "BQL"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                   "BQL: below quantitation limit"   
#> [3] "MISS: missing observations (BQL)" "OBS: observations"
bq_col <- "BLQ"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                   "BLQ: below limit of quantitation"
#> [3] "MISS: missing observations (BLQ)" "OBS: observations"
```

<sup>Created on 2022-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kylebaron** [comment]
And then handling if we just don't want BLQ

``` r
library(pmtables)

bq_col <- "BQL"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                   "BQL: below quantitation limit"   
#> [3] "MISS: missing observations (BQL)" "OBS: observations"
bq_col <- "BLQ"
pt_data_inventory_notes(bq_col)
#> [1] "SUBJ: subjects"                   "BLQ: below limit of quantitation"
#> [3] "MISS: missing observations (BLQ)" "OBS: observations"
pt_data_inventory_notes(bq_col, drop_bql = TRUE)
#> [1] "SUBJ: subjects"             "MISS: missing observations"
#> [3] "OBS: observations"
```

<sup>Created on 2022-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by KatherineKayMRG** [comment]
Also, did we ever come to a decision regarding "quantitation" vs "quantification"?

**Comment by kylebaron** [comment]
We can change that too; will check on columns and make sure it's right.

**Comment by kylebaron** [comment]
Closer ...
<img width="510" alt="Screen Shot 2022-01-13 at 5 46 54 PM" src="https://user-images.githubusercontent.com/16908301/149426562-113e4a5b-3ea3-4824-8ac8-e36bc7789d64.png">
<img width="506" alt="Screen Shot 2022-01-13 at 5 46 47 PM" src="https://user-images.githubusercontent.com/16908301/149426563-4c5998ee-36b0-4613-b0b7-c85fa6cfa0ec.png">
<img width="499" alt="Screen Shot 2022-01-13 at 5 46 44 PM" src="https://user-images.githubusercontent.com/16908301/149426565-199192a9-a0b9-46c8-ac27-255a7dfec8a6.png">

**Comment by KatherineKayMRG** [comment]
That looks good to me :)

**Comment by kylebaron** [comment]
Cool; I'll get this cleaned up and documented etc. Thanks for the report.  Also ... can you move the text starting with `For example` out of the main post and into a comment? I'd like to keep this issue open and that can't be there in the validation docs.

**Comment by KatherineKayMRG** [comment]
Thanks for getting to this so quickly!

**Comment by KatherineKayMRG** [comment]
Sorry, I just realised what you meant but now it won't let me change my original comment

**Comment by KatherineKayMRG** [comment]
oh nm, looks like you managed it
