### ISSUE TITLE
tabularray

### ISSUE THREAD

**Issue by Mutaz94** [metrumresearchgroup/pmtables#323]
Hi folks: 

Have you consider moving the structure to `tabularray` [](https://ctan.org/pkg/tabularray?lang=en)?

It's giving much convenient interface for tables (without the need for tabular vs longtable). A nice reading: https://tug.org/TUGboat/tb44-1/tb136duck-tabularray.pdf

**Comment by kylebaron** [comment]
Hi @Mutaz94  - 

Thanks for the link. I hadn't heard of this before so, no, haven't considered re-writing all the code to work through tabularray.

Kyle

**Comment by Mutaz94** [comment]
Thanks! I have been playing with it recently and i saw it overcome some issues with longtable mostly the caption and labels and list of tables numbering. I can close this and i might fork the repo and do some testing.
