### ISSUE TITLE
pt_cat_long_notes issue

### ISSUE THREAD

**Issue by cstevee2** [metrumresearchgroup/pmtables#324]
Was not able to use the code to remove the summary notes.  Got too many arguments error when using "pt_cat_long_notes(include_n = FALSE, note_add = FALSE) "

**Comment by kylebaron** [comment]
Thanks for the report, @cstevee2

If you want to remove the notes from `pt_cat_long()` call, can you try this?

``` r
library(pmtables)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

pt_cat_long(pmt_first, cols = "SEXf, CPf") %>%
  st_new() %>%
  st_notes_rm() %>%
  st_as_image()
```

<img src="https://i.imgur.com/QcPpevj.png" width="1897" />

<sup>Created on 2024-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


If you're doing something else (maybe editing the notes), can you share some code and I can help get you there.

Kyle
